name: Windows - RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/huuhieu17/freerdp/refs/heads/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Enable RDP and open PORt
        run: cmd /c enable_rdp_and_open_port.bat

      - name: Get RDP info
        run: cmd /c get_public_ip.bat

      - name: Time Counter
        run: python time.py


